# Generated by Django 4.2.1 on 2023-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='image', verbose_name='イメージ画像'),
            preserve_default='True',
        ),
    ]
